### ISSUE TITLE
Issue fetching meta tags for url

### ISSUE THREAD

**Issue by cdrandin** [jvanasco/metadata_parser#23]
This is potentially a multi-part issue.

## Parsing Reddit links yield no metadata ##

The parser doesn't do a good job at parsing reddit links.

Some example ones to try out:

* https://reddit.com/r/funny/comments/dghqzb/aubrey_plaza_is_the_best/
* https://reddit.com/r/playark/comments/dghy5k/the_devs_when_every_new_dlc_launch_has_problems/

This is my current configuration

```python
page = metadata_parser.MetadataParser(
    url=url,
    force_doctype=True,
    search_head_only=False,
    only_parse_http_ok=False,
    support_malformed=True,
)

print(page.metadata) # results in \/
```

```json
{
    "og": {
        "ttl": "600",
        "site_name": "reddit"
    },
    "meta": {
        "charset": "utf-8",
        "robots": "noindex,nofollow",
        "viewport": "width=device-width, initial-scale=1",
        "referrer": "origin-when-cross-origin",
        "og:ttl": "600",
        "og:site_name": "reddit",
        "twitter:site": "@reddit",
        "twitter:card": "summary",
        "msapplication-TileColor": "#ffffff",
        "msapplication-TileImage": "https://www.redditstatic.com/desktop2x/img/favicon/ms-icon-144x144.png",
        "theme-color": "#ffffff"
    },
    "dc": {},
    "page": {
        "title": "reddit: the front page of the internet"
    },
    "twitter": {},
    "_internal": {
        "url": "https://reddit.com/r/playark/comments/dghy5k/the_devs_when_every_new_dlc_launch_has_problems/",
        "url_actual": "https://www.reddit.com/r/playark/comments/dghy5k/the_devs_when_every_new_dlc_launch_has_problems/"
    },
    "_v": 1
}
```

Which doesn't give any sort of metadata.

As I fetch the page with `wget` these are the meta tags

```html
    <meta property="og:ttl" content="600" />
    <meta property="og:site_name" content="reddit" />
    <meta property="twitter:site" content="@reddit" />
    <meta property="twitter:card" content="summary" />
    <meta property="og:title" content="r/funny - Aubrey Plaza is the best .." />
    <meta property="twitter:title" content="r/funny - Aubrey Plaza is the best .." />
    <meta property="og:type" content="video" />
    <meta property="og:url" content="https://www.reddit.com/r/funny/comments/dghqzb/aubrey_plaza_is_the_best/" />
    <meta property="og:description" content="35,617 votes and 1,417 comments so far on Reddit" />
    <meta property="og:image" content="https://external-preview.redd.it/TUjjM2vfW7r3nggvDvOT8WwCYb-HnGuU_B8Ki3V4kec.png?format=pjpg&amp;auto=webp&amp;s=3c2cad4eadea2da462c6cde42ce475722dfff40f" />
    <meta property="og:image:width" content="960" />
    <meta property="og:image:height" content="540" />
    <meta property="twitter:image" content="https://external-preview.redd.it/TUjjM2vfW7r3nggvDvOT8WwCYb-HnGuU_B8Ki3V4kec.png?format=pjpg&amp;auto=webp&amp;s=3c2cad4eadea2da462c6cde42ce475722dfff40f" />
```

## Parsing Reddit links without `only_parse_http_ok=False` always fails ##

```python
page = metadata_parser.MetadataParser(
    url=url,
    force_doctype=True,
    search_head_only=False,
    support_malformed=True,
)

# results in an error

File ".../env/lib/python3.7/site-packages/metadata_parser/__init__.py", line 1273, in __init__
  retry_dropped_without_headers=retry_dropped_without_headers,
File ".../env/lib/python3.7/site-packages/metadata_parser/__init__.py", line 1469, in fetch_url
  metadataParser=self,
metadata_parser.NotParsableFetchError: NotParsableFetchError: Status Code is not 200 | 502 | None

```

## weird note ##

After trying to get it to work with different configurations I was able to parse it once. I even tried with the exact same configuration. It no longer works.

Seems to work randomly or perhaps Reddit servers are preventing it.

**Comment by cdrandin** [comment]
So, after writing all this up and doing more testing. I figure out my issue. I was hoping to just leave this here for others in case they encounter a similar issue.

But the reason Reddit links weren't working is because it was sending no meta links. I decided to fetch the html myself with requests and I found out that meta tags weren't being sent.

After a bit of research and had to insert a User-Agent to let it know I was a potential user.

So, I then did the following

```python
headers = { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

page=metadata_parser.MetadataParser(
    url = url,
    url_headers = headers,
    search_head_only = False,
)
```

and it works now for all links I had trouble with.

**Comment by jvanasco** [comment]
> Parsing Reddit links without only_parse_http_ok=False always fails

That's because Reddit is sending a 502 gateway status code. note this line:

> metadata_parser.NotParsableFetchError: NotParsableFetchError: Status Code is not 200 | 502 | None

If you set a breakpoint (`pdb.set_trace()`) over here, you'll be able to explore this more:

https://github.com/jvanasco/metadata_parser/blob/master/metadata_parser/__init__.py#L1636-L1641

So reddit has a 502 gateway error, but is still sending content as if it were 200. Perhaps this is a cached fallback, or perhaps it's a mechanism against programmatic access.  I have no idea.  There are some CDNs that do similar things.

you can also explore the response on the result object, and re-parse the html...

    result = metadata_parser.MetadataParser(url=...

    print(result)
    pprint.pprint(dir(result))

    print(result.response)
    pprint.pprint(dir(result.response))

    result2 = metadata_parser.MetadataParser(html=result.response.text)

The `response` attribute is the actual item from `requests`, and is stashed there for debugging or re-parsing with different options.

Like many other large sites, Reddit's infrastructure has some implementation details and/or defenses against programmatic access that can make analyzing it's content difficult.  If you run your request a few times, from different IPs with different cache timeouts, you'll sometimes get headers and sometimes not.

There are also some CDNs that cause similar issues.  IIRC, Akamai and Verizon could both get a 'blocked' version of a page stuck on a cache server, and you'd have to wait for it to expire OR access it from an ip address in another geographic zone

I wish there were a reliable answer to this, but this is one of those "ugh" problems.

**Comment by cdrandin** [comment]
Yup, definitely and I have also done parsing it manually and passing html content directly.

So, for the most what has been working after abusively testing it within my small timespan is that added a user agent has made fetching metadata reliable for now.
