### ISSUE TITLE
Trouble retrieving (some) individual items

### ISSUE THREAD

**Issue by WeaverStever** [jvanasco/metadata_parser#7]
I am seeing an anomaly (url side) between the two functions "page.metadata" and "page.get_metadata('fieldname')".  I can't seem to retrieve some fields with  "page.get_metadata('fieldname')" that are displayed by calling the "page.metadata".  The fields are prefixed with "article:" but I am able to retrieve some fields (items) with that prefix.

For instance I can retrieve the item meta name="article.headline", but cannot retrieve meta name="article.access" and meta name="article.published" (an ISO 8601 date), with both returning None.

Again, I can see that the data was retrieved in the dict, I just cant seem to coax it out with the "page.get_metadata('fieldname')" function.  I'm aware that the "article:" prefix is beyond the scope, but I am able to retrieve the "article.headline" at the same nested level.

Thanks!

**Comment by jvanasco** [comment]
So a few things, using the example from the WSJ that you messaged me with earlier:

You should be able to your info from the current package though.  It just recodes the metadata into a dict -- there are no special rules or processing. Try using the commandline like this:

	>>> from metadata_parser import MetadataParser
	>>> from pprint import pprint
	>>> url = 'http://www.wsj.com/articles/police-widen-search-for-tennessee-officers-killer-person-of-interest-held-1438539422'
	>>> parsed = MetadataParser(url=url)
	>>> pprint(parsed.metadata)

That will show the dict below.  it's just catching the metadata into a dict that is managed by several known schemas (og, dc, meta, raw page data, etc)

The parsed object caches a lot of data

	>>> dir(parsed)
	>>> dir(parsed.response)
	>>> print parsed.response.text

If you're using this as part of a script, you can use the python debugger (standard library) to set breakpoints

	import pdb
	...
	parsed = MetadataParser(url=url)
	pdb.set_trace()


That will pause the script and let you inspect the objects/state.

these two are useful:

1. `parsed.soup`  # the BeautifulSoup object
2. `parsed.response`  # the actual response object (raw html, headers, etc)

I would check the parsed object to see what the response returns.

Several websites, including the WSJ, have aggressive Firewalls that are used for ratelimiting and spider identification.  I recall the WSJ have a very low threshold and instead of raising an error, it gives a 200OK and served a CAPTCHA page.  If that is still the case, you may need to examine the response object to see if it's a real page or not.

If you do need to write advanced rules, the `parsed.soup` is the actual `BeautifulSoup` document.

Now, if you look at the dict (copied below), you will hopefully notice an small difference -- the WSJ uses both an `article:` and `article.` prefix.  You're searching for `article:published` but the data is in `article.published`.  

This is most likely because the `article:` namespace is typically used by a hybrid of OpenGraph and proprietary Facebook tags, while `article.` doesn't respond to anything that is well known.

Doing a bit of digging...  The following things seem on ONLY appear on pages from the wsj:

* this header tag `<!-- TESLA DESKTOP16 V1 -->`
* a dotted namespace with keys like `article.origheadline` and `page.content.source`

I would guess that the big problem you're facing is that the published time for WSJ articles appears in a proprietary tag.  You can access it easily with this package, but it's going to be in the WSJ's `article.published` field, not the OpenGraph(http://ogp.me/#type_article) `article:published_time` that you're expecting.


	{'dc': {},
	 'meta': {'Content-Type': u'text/html; charset=UTF-8',
			  'X-UA-Compatible': 'IE=edge',
			  'article.access': 'paid',
			  'article.created': '2015-08-02T18:17:00.000Z',
			  'article.headline': u'Memphis police hunt suspect in officer\u2019s killing',
			  'article.id': 'SB11927926087197634032704581146521624988188',
			  'article.origheadline': u'Police Widen Search for Tennessee Officer\u2019s Killer; Person of Interest Held',
			  'article.page': 'US',
			  'article.published': '2015-08-03T02:48:00.000Z',
			  'article.section': 'US',
			  'article.summary': 'A search was under way Sunday night for a 29-year-old man identified as the lead suspect in the fatal shooting of a Memphis, Tenn., police officer during a traffic stop Saturday, authorities said.',
			  'article.template': 'snippet',
			  'article.type': 'U.S. News',
			  'article.updated': '2015-08-03T02:48:00.000Z',
			  'article:image_count': '1',
			  'article:internal_link_count': '1',
			  'article:publisher': 'https://www.facebook.com/wsj',
			  'article:word_count': '284',
			  'author': 'Ashby Jones',
			  'cXenseParse:candybar:image': 'http://si.wsj.net/public/resources/images/BN-JR273_MEMPHI_E_20150802214205.jpg',
			  'cXenseParse:poptart:image': 'http://si.wsj.net/public/resources/images/BN-JR273_MEMPHI_D_20150802214205.jpg',
			  'description': 'A search was under way Sunday night for a 29-year-old man identified as the lead suspect in the fatal shooting of a Memphis, Tenn., police officer during a traffic stop Saturday, authorities said.',
			  'dj.asn': 'i-c512',
			  'fb:app_id': '368513495882',
			  'keywords': 'memphis shooting,police officer shot,sean bolton,tennessee officer shooting,tennessee shooting,Sean Bolton,political,general news,national security,crime,courts,law enforcement,murder,manslaughter',
			  'language': 'en-US',
			  'news_keywords': 'memphis shooting,police officer shot,sean bolton,tennessee officer shooting,tennessee shooting,Sean Bolton,political,general news,national security,crime',
			  'og:description': 'A search was under way Sunday night for a 29-year-old man identified as the lead suspect in the fatal shooting of a Memphis, Tenn., police officer during a traffic stop Saturday, authorities said.',
			  'og:image': 'http://si.wsj.net/public/resources/images/BN-JR273_MEMPHI_G_20150802214205.jpg',
			  'og:image:height': '369',
			  'og:image:width': '553',
			  'og:locale': 'en_US',
			  'og:site_name': 'WSJ',
			  'og:title': u'Memphis Police Hunt Suspect in Officer\u2019s Killing',
			  'og:type': 'article',
			  'og:url': 'http://www.wsj.com/articles/police-widen-search-for-tennessee-officers-killer-person-of-interest-held-1438539422',
			  'page.content.format': 'responsive',
			  'page.content.source': 'WSJ Online Article',
			  'page.content.type': 'article',
			  'page.region': 'na,us',
			  'page.section': 'Article',
			  'page.site': 'wsj',
			  'robots': 'noarchive,noodp',
			  'testkeys': 'C',
			  'twitter:card': 'summary_large_image',
			  'twitter:creator': '@jonesashby',
			  'twitter:description': 'A search was under way Sunday night for a 29-year-old man identified as the lead suspect in the fatal shooting of a Memphis, Tenn., police officer during a traffic stop Saturday, authorities said.',
			  'twitter:domain': 'wsj.com',
			  'twitter:image': 'http://si.wsj.net/public/resources/images/BN-JR273_MEMPHI_D_20150802214205.jpg',
			  'twitter:image:src': 'http://si.wsj.net/public/resources/images/BN-JR273_MEMPHI_G_20150802214205.jpg',
			  'twitter:site': '@WSJ',
			  'twitter:title': u'Memphis Police Hunt Suspect in Officer\u2019s Killing',
			  'user.exp': 'default',
			  'user.type': 'nonsubscriber',
			  'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'},
	 'og': {'description': 'A search was under way Sunday night for a 29-year-old man identified as the lead suspect in the fatal shooting of a Memphis, Tenn., police officer during a traffic stop Saturday, authorities said.',
			'image': 'http://si.wsj.net/public/resources/images/BN-JR273_MEMPHI_G_20150802214205.jpg',
			'image:height': '369',
			'image:width': '553',
			'locale': 'en_US',
			'site_name': 'WSJ',
			'title': u'Memphis Police Hunt Suspect in Officer\u2019s Killing',
			'type': 'article',
			'url': 'http://www.wsj.com/articles/police-widen-search-for-tennessee-officers-killer-person-of-interest-held-1438539422'},
	 'page': {'canonical': 'http://www.wsj.com/articles/police-widen-search-for-tennessee-officers-killer-person-of-interest-held-1438539422',
			  'title': u'\n      Memphis Police Hunt Suspect in Officer\u2019s Killing - WSJ\n    '},
	 'twitter': {}}
